# ==========================================================================
# CRE WORKFLOW SETTINGS FILE
# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "randomness-staging"
  workflow-artifacts:
    workflow-path: "."
    config-path: "./config.staging.json"
    secrets-path: ""

# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "randomness-production"
  workflow-artifacts:
    workflow-path: "."
    config-path: "./config.production.json"
    secrets-path: ""
