# ==========================================================================
# CRE WORKFLOW SETTINGS FILE
# ==========================================================================
# Workflow-specific settings for CRE CLI targets.
# Each target defines user-workflow and workflow-artifacts groups.
# Settings here override CRE Project Settings File values.
#
# Example custom target:
# my-target:
#   user-workflow:
#     workflow-name: "MyExampleWorkflow"    # Required: Workflow Registry name
#   workflow-artifacts:
#     workflow-path: "./main.ts"            # Path to workflow entry point
#     config-path: "./config.yaml"          # Path to config file
#     secrets-path: "../secrets.yaml"       # Path to secrets file (project root by default)

# ==========================================================================
local-simulation:
  user-workflow:
    workflow-name: "custom-data-feed-workflow"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: "../secrets.yaml"

# ==========================================================================
staging:
  user-workflow:
    workflow-name: "custom-data-feed-workflow"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: ""
    secrets-path: ""
    