# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia-base-1
      url: https://rpcs.cldev.sh/base/sepolia

# ==========================================================================
production-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
    - chain-name: ethereum-mainnet
      url: https://ethereum-rpc.publicnode.com
