# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
# Project-specific settings for CRE CLI targets.
# Each target defines cre-cli, account, and rpcs groups.
#
# Example custom target:
# my-target:
#   account:
#     workflow-owner-address: "0x123..."            # Optional: Owner wallet/MSIG address (used for --unsigned transactions)
#   rpcs:
#     - chain-name: ethereum-mainnet                # Required: Chain RPC endpoints
#       url: "https://mainnet.infura.io/v3/KEY"

# ==========================================================================
staging-settings:
  rpcs:
    - chain-name: ethereum-mainnet-arbitrum-1
      url: https://sepolia.infura.io/v3/YOUR_API_KEY

# ==========================================================================
production-settings:
  rpcs:
    - chain-name: ethereum-mainnet-arbitrum-1
      url: https://sepolia.infura.io/v3/YOUR_API_KEY
